<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType><TargetFramework>net48</TargetFramework>
    <PlatformTarget>x64</PlatformTarget><LangVersion>latest</LangVersion><AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <DefaultItemExcludes>$(DefaultItemExcludes);**\bin\**;**\obj\**</DefaultItemExcludes>
    <AutoGenerateBindingRedirects>true</AutoGenerateBindingRedirects><GenerateBindingRedirectsOutputType>true</GenerateBindingRedirectsOutputType>
  </PropertyGroup>
  <ItemGroup><ProjectReference Include="..\..\CIS_WebInspector.csproj" /></ItemGroup>
  <Target Name="CopyRuntime" AfterTargets="Build">
    <Copy SourceFiles="..\..\bin\x64\$(Configuration)\net48\OpenCvSharpExtern.dll;..\..\bin\x64\$(Configuration)\net48\CISVisionCore.dll" DestinationFolder="$(OutputPath)" SkipUnchangedFiles="true" />
    <ItemGroup><Models Include="..\..\Assets\WeChatQRCode\**\*" /></ItemGroup>
    <Copy SourceFiles="@(Models)" DestinationFiles="@(Models->'$(OutputPath)Assets\WeChatQRCode\%(RecursiveDir)%(Filename)%(Extension)')" SkipUnchangedFiles="true" />
  </Target>
</Project>
